- name: query users repositories where he is at least developer
  uri:
    url: "https://{{ gitlab_domain }}/api/v4/projects/min_access_level=30?private_token={{ GITLAB_TOKEN }}"
    method: GET
    return_content: yes
    timeout: 120
  register: result

- name: extract repositories list
  set_fact:
    projectlist: "{{ result.content | from_json }}"

- name: create directory for repo clones
  file:
    path: "{{ ansible_user_dir }}/{{ gitlab_domain }}/{{ item.namespace.name }}"
    state: directory
  with_item: "{{ projectlist }}"

- name: clone repositories
  git:
    repo: "{{ item.ssh_url_to_repo }}"
    dest: "{{ ansible_user_dir }}/{{ gitlab_domain }}/{{ item.path_with_namespace }}"
  with_items: "{{ projectlist }}"
