- name: query user
  uri:
    url: "https://{{ gitlab_domain }}/api/v4/users?username={{ username }};private_token={{ GITLAB_TOKEN }}"
    method: GET
    return_content: yes
    timeout: 120
  register: result

- name: log query
  debug:
    var: result.content

- name: extract user id
  set_fact:
    userid: "{{ (result.content | from_json)[0].id }}"

- name: query users repositories
  uri:
    url: "https://{{ gitlab_domain }}/api/v4/users/{{ userid }}/projects?private_token={{ GITLAB_TOKEN }}"
    method: GET
    return_content: yes
    timeout: 120
  register: result

- name: extract repositories list
  set_fact:
    projectlist: "{{ result.content | from_json }}"

- name: create directory for repo clones
  file:
    path: "{{ ansible_user_dir }}/{{ gitlab_domain }}/{{ username }}"
    state: directory

- name: clone repositories
  git:
    repo: "{{ item.ssh_url_to_repo }}"
    dest: "{{ ansible_user_dir }}/{{ gitlab_domain }}/{{ username }}/{{ item.name }}"
  with_items: "{{ projectlist }}"
